version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/api_quotes
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - '.env'
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - '.env'
