version: '3'
services:
  web:
    build: .
    container_name: 'rails_app'
    command: bash -c "rm -f tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/api_quotes
    depends_on:
      - db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - '.env'
  db:
    image: mongo
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    env_file:
      - '.env'
